# PostgreSQL configuration
# Install PostgreSQL if needed: https://www.postgresql.org/download/

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: lifeboard_development

test:
  <<: *default
  database: lifeboard_test

production:
  <<: *default
  database: lifeboard_production
  username: lifeboard
  password: <%= ENV['LIFEBOARD_DATABASE_PASSWORD'] %>
